name: pages

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: docs

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: master
        force_orphan: true
